apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice
spec:
  replicas: {{ .Values.rep_set.microservice }}
  selector:
    matchLabels:
      app: microservice
      version: latest
  template:
    metadata:
      labels:
        app: microservice
        version: latest
    spec:
      volumes:
      - name: microservice-storage
        persistentVolumeClaim:
          claimName: microservice-pvc
      containers:
        - name: microservice
          env:          
            - name: MONGO_URI
              value: {{ .Values.MONGO_URI }}
          image: {{ .Values.images.microservice }}
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - name: microservice-storage
              mountPath: /app/logs/

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: {{ .Values.rep_set.mongodb }}
  selector:
    matchLabels:
      app: mongodb
      version: latest
  template:
    metadata:
      labels:
        app: mongodb
        version: latest
    spec:
      hostname: mongodb-container
      volumes:
      - name: mongodb-storage
        persistentVolumeClaim:
          claimName: mongodb-pvc
      containers:
        - name: mongodb
          image: {{ .Values.images.mongodb }}

          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-storage
              mountPath: /data/db
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
        