apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  labels: 
    type: local
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/mongofiles/mongodb # This is the path on the host where the data will be stored
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "mongodb"
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: microservice-pv
  labels: 
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/mongofiles/logs
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "microservice"
