name: Pipeline for Details_App

on:
  push:
    branches:
      - main

jobs:
  tests:
    name: Test Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install pytest
        run: |
            ## Installing poetry and pytest 
            sudo apt update -y
            sudo apt upgrade -y
            sudo apt install -y python3 
            pip install poetry
            pip install pytest

            # Install project dependencies into the Poetry environment
            poetry lock
            poetry install
            # Run pytest
            poetry run pytest src/test.py

  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: tests
    environment: ${{ github.ref_name }}
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ vars.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}

      - name: Build and push Docker image(One with latest, and the other with the run number as the tag)
        id: push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ vars.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:2.1.${{ github.run_number }}
            ${{ vars.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:${{vars.IMAGE_TAG}}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ vars.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:2.1.${{ github.run_number }}
          subject-digest: ${{ steps.push.outputs.digest }}
  
## Marking the deployment, since it will fail. It needs relevant details needed for the deployment - K8S Master's IP, SSH username and key, and the deployment name running the container of the app
#   deploy_to_k8s:
#     name: Deploying to K8S
#     runs-on: ubuntu-latest
#     needs: push_to_registry
#     environment: ${{ github.ref_name }}
#     steps:
#         - name: check out
#           run: |
#             screw cat ${{ secrets.SSH_KEY }} | ssh -i /dev/stdin ${{ vars.SSH_USERNAME }}@${{ vars.MASTER_IP }} "kubectl rollout ${{ vars.DEPLOYMENT_NAME }}" 